package com.example.birdsforms;

import com.google.firebase.firestore.DocumentSnapshot;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;

public class PasswordVerifier {

    private String login;
    private String password;
    List<DocumentSnapshot> myListOfDocuments;
    boolean b = false;
    private void as(List<DocumentSnapshot> x) {
        this.myListOfDocuments = x;
    }


    public PasswordVerifier(String login, String password) {
        this.login = login;
        this.password = password;
    }

    private String getPasswordFromDB(String login) {

        return null;
    }

    public static String encryptThisString(String input)
    {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");

            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);

            String hashtext = no.toString(16);

            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }

            return hashtext;
        }

        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String args[]) throws NoSuchAlgorithmException
    {

        System.out.println("HashCode Generated by SHA-512 for: ");

        String s1 = "password";
        System.out.println("\n" + s1 + " : " + encryptThisString(s1));

        String s2 = "userPassword";
        System.out.println("\n" + s2 + " : " + encryptThisString(s2));
    }
}